### ISSUE TITLE
Possibility of add a Machine Learning module?

### ISSUE THREAD

**Issue by fergunet** [tscmoo/tsc-bwai#1]
Hi @tscmoo !

I am Pablo García, from University of Granada. Me and my colleague Alberto Tonda are doing research on Starcraft AI. We heard the commentator of the SCAIT youtube video that you wanted to add some kind of Machine Learning module to your bot. As our research line is quite related with ML, optimization and Data mining you can contact with us via this issue (or to pablogarcia @ ugr .es) to start some kind of collaboration if you like :)

Thanks for your time and congratulations for your bot! :D

**Comment by tscmoo** [comment]
Hi, sorry for the late response.

I'm not interested in a collaboration at the moment. I did try to apply neural networks to learn what to build in response to scouted units, but the effectiveness was inconclusive. I'm sure it could be applied successfully, but I don't have the time for it right now. I might come back to it at some point, so maybe then.
